
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

In [ ]:
#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [27]:
a=np.zeros(10)
print(a, "\n")
a.size

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 



10

In [23]:
#### 3. Create a null vector of size 10 but the fifth value which is 1.

In [25]:
x = np.zeros(10); x[4] = 1
print (x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [121]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [43]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [42]:
grid=np.arange(0, 9).reshape ((3, 3))
grid

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [51]:
x = np.array([1,2,0,0,4,0])
np.where(x == 0)[0]


array([2, 3, 5], dtype=int64)

In [ ]:
#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [52]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [64]:
b = np.random.random((3,3,3))
print(b)

[[[0.55305219 0.9467336  0.77801585]
  [0.78506635 0.05281996 0.70908399]
  [0.58662306 0.59265896 0.77882172]]

 [[0.01341255 0.86822136 0.20084136]
  [0.74326219 0.86509048 0.0292994 ]
  [0.06923818 0.09678043 0.26257941]]

 [[0.15039019 0.38491278 0.86638189]
  [0.10356717 0.18219067 0.51022115]
  [0.47259567 0.29441597 0.24020312]]]


In [ ]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [72]:
p = np.random.random((10,10))


x=p.min()
y=p.max()

print(x)
print(y)

np.min(p)
np.max(p)

0.0052088744985469
0.9988215704561824


In [ ]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [74]:
a = np.random.random((30))
a

np.mean(a)

0.5073527727138386

In [ ]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`


In [95]:
from scipy import sparse

y=np.diag([1,2,3,4])                                                                    
y

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [123]:
k = np.random.random((5,5))
matrix= (k-np.mean(k)/np.std(k))
k

array([[0.6150225 , 0.44591283, 0.07593783, 0.68847162, 0.39900232],
       [0.52448624, 0.07959594, 0.49577518, 0.6631403 , 0.08160341],
       [0.88331587, 0.6124718 , 0.63984401, 0.57370472, 0.94700604],
       [0.9439473 , 0.3794944 , 0.32201978, 0.13023661, 0.22502297],
       [0.47034452, 0.40306267, 0.77017167, 0.56255331, 0.86616251]])

In [100]:
f = np.random.random((5,5))
mean=np.mean(f)
std=np.std(f)
print(f)
print(mean)
print(std)
k=(f-mean)/std
k

[[0.49387209 0.10073219 0.63613972 0.44020979 0.36797901]
 [0.44564593 0.85053561 0.46220261 0.48126311 0.74149382]
 [0.25958873 0.65009452 0.35955875 0.57868698 0.86591196]
 [0.7345116  0.58196106 0.19342506 0.73567215 0.68903331]
 [0.7938702  0.60132723 0.29907948 0.07070994 0.46502172]]
0.5159410630261012
0.21800780949879822


array([[-0.10123019, -1.90455964,  0.55135023, -0.34737872, -0.67870068],
       [-0.32244318,  1.53478238, -0.24649782, -0.1590675 ,  1.03460862],
       [-1.17588601,  0.61536078, -0.71732438,  0.28781501,  1.60531356],
       [ 1.00258123,  0.30283317, -1.47937821,  1.00790466,  0.79397271],
       [ 1.27485862,  0.39166563, -0.99474225, -2.04227143, -0.23356661]])

In [102]:
#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

SyntaxError: invalid syntax (3096181724.py, line 2)

In [109]:
j=np.arange(0, 20, 2)
k=np.arange(10, 30, 2)
m= np.intersect1d(j,k)
m

array([10, 12, 14, 16, 18])

In [ ]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [113]:
A = np.random.random((10))
np.sort(A)

array([0.15800827, 0.18605199, 0.25556057, 0.30924305, 0.38045162,
       0.43584273, 0.48246582, 0.49778601, 0.77019159, 0.88004896])

In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [118]:
A = np.random.random((10))

mx = max(A)
for i in range(len(A)):
    if A[i] == mx:
        A[i] = 0
A


array([0.14598612, 0.47470559, 0.        , 0.11975015, 0.36085359,
       0.49199264, 0.50979988, 0.13564375, 0.28734281, 0.66335516])

In [ ]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [120]:
A = np.random.random((10,2))

mean1=np.mean(A)

k=(A-mean1)
k

array([[ 0.31878387,  0.05149461],
       [ 0.35503849, -0.42752204],
       [-0.26510384,  0.26688831],
       [-0.08124364,  0.17569823],
       [-0.02390455,  0.0167518 ],
       [ 0.1870084 , -0.20842618],
       [-0.03982434, -0.18084946],
       [-0.37013281, -0.11307095],
       [ 0.21819471,  0.20085603],
       [-0.28412165,  0.20348502]])

In [ ]:
#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`